name: Docker Image Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./src  --tag dasunnimantha/k8s-express
    - name: Log in to Docker Hub
      run: docker login https://registry.dasunnimantha.com -u ${{ secrets.MY_REG_USERNAME }} -p ${{ secrets.MY_REG_PASSWORD }}
    - name: Push image to DockerHub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/k8s-express
